name: Benchmark

on:
  push:
    branches:
      - community

jobs:
  docker:
    uses: mrivnak/game-of-life/.github/workflows/publish-image.yml@community

  benchmark:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull
        run: docker pull ghcr.io/mrivnak/game-of-life:community

      - name: Run benchmark
        run: |
          docker run --name game-of-life ghcr.io/mrivnak/game-of-life:community
          docker cp game-of-life:/app/benchmark_results.txt ./benchmark_results.txt
          echo 'BENCHMARK_RESULTS<<EOF' >> $GITHUB_ENV
          cat ./benchmark_results.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Post benchmark results
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Benchmark Results
          conclusion: ${{ job.status }}
          output: |
            {"title":"Benchmark Results","summary":"${{ env.BENCHMARK_RESULTS }}"}
